apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimitsMemoryOnly
metadata:
  name: container-must-have-limits-only-memory
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    memory: "1Gi"